function [R] = correlation_coefficient_matrix_creating(purchase_matrix)
%CORRELATION_COEFFICIENT_MATRIX_CREATING  Generate correlation coefficient matrix.
% input
% purchase_matrix: The user-item purchase matrix generated by 
% "matrix_creating.m".
% output
% R: % correlation coefficient matrix, and row i, column j for correlation
% coefficient r_i(j).

global_CTR = sum(purchase_matrix) ./ size(purchase_matrix , 1);   %CTR for each item across all users.
R = (purchase_matrix' * purchase_matrix) ./ sum(purchase_matrix)' - global_CTR;   %correlation coefficient matrix, row i, column j;

end

